### ISSUE TITLE
can this plugin support grunt options?

### ISSUE THREAD

**Issue by dzuluaga** [tvooo/sublime-grunt#100]
This is great. I'm looking for ways to pass options such as environment, debug, stack, etc. e.g.

``` js
grunt --env=test --username=$ae_username --password=$ae_password
```

Thanks!

**Comment by tvooo** [comment]
It does not. I'm considering adding custom arguments and defaults to individual *project* settings, but I'm not sure yet how to do it. Would welcome any ideas!

**Comment by tvooo** [comment]
Repository was moved to https://github.com/sptndc/sublime-grunt
Please re-file any issues that still exist.
