### ISSUE TITLE
Remove SublimeGrunt from the package registry

### ISSUE THREAD

**Issue by tvooo** [tvooo/sublime-grunt#111]
I don't have the time or interest to maintain it anymore.
If someone wants to take over, I'm happy to hand it to them! Otherwise I'll be removing it from the registry.

**Comment by Kristinita** [comment]
@tvooo , please, add [**unmantained**](http://unmaintained.tech/) badge and announcement in [**Sublime Text forum**](https://forum.sublimetext.com/).

Thanks.

**Comment by tvooo** [comment]
Done both.
