### ISSUE TITLE
Gruntfile not found - (already tried #77 and #97)

### ISSUE THREAD

**Issue by jaykobo** [tvooo/sublime-grunt#113]
If the Gruntfile.js is on the root project folder there is no problem.

But sometimes the Gruntfile.js is located in a subfolder. I already tried a lot of things.. looked at issue #77 and tried the tips from the comments (from @mihirgokani007 and @aolin480). I've also tried the changes in main.py from #97 but nothing helps.

In my example the project folder is located:
`Projects/client/projectname`

And the Gruntfile.js is located: 
`Projects/client/projectname/_sources/Gruntfile.js`

Here are a couple of solutions i tried in my .sublime-project:

```javascript
{
    "folders":
    [
        {
            // example project path
            "path": "/Projects/client/projectname"
        }
    ],
    "settings":
    [
        {
            "SublimeGrunt":
            {
                "gruntfile_paths":
                [
                    "/_sources"
                ]
            }
        }
    ],
    "settings":
    [
        {
            "gruntfile_paths":
            [
                "/_sources"
            ]
        }
    ],
    "settings": {
        "SublimeGrunt": {
            "gruntfile_paths":
            [
                "/_sources"
            ]
        }
    },
    "SublimeGrunt":
    {
        "gruntfile_paths":
        [
            "/_sources"
        ]
    },
}
```

Is there any chance or hint i missed to make it work? Any help is **really appreciated!**

**Comment by tvooo** [comment]
Have you tried omitting the `/` at the front of your path? So make it just `"_sources"`.

**Comment by jaykobo** [comment]
Hey, thanks for your reply. Yes I tried all of them: `"_sources"`, `"/_sources"` and `"/_sources/"`. Unfortunately without success.

**Comment by englishextra** [comment]
@jaykobo The package's broken

**Comment by tvooo** [comment]
The package is deprecated and unmaintained. I'll remove it from Package Control when I get to it. Sorry about that. If anyone wants to pick it up, I'm happy to transfer maintainership.

**Comment by jaykobo** [comment]
Oh.. okay. Too bad. Thanks anyway for your reply.

**Comment by arjunrbery** [comment]
Hey @tvooo 
Quick and dirty change to make it function on my device for now. Starts on line 70.
https://github.com/tvooo/sublime-grunt/blob/bf795fd342d1a40555f58adcc46833be571ab46b/main.py#L70
to
``` python
        self.folder_paths = get_grunt_file_paths()
        self.grunt_files = []
        self.folders = []
        for f in self.window.folders():
            self.folders.append(f)
            for fp in self.folder_paths:
                self.folders.append(f + fp)

        for f in self.folders:
```

**Comment by tvooo** [comment]
Repository was moved to https://github.com/sptndc/sublime-grunt
Please re-file any issues that still exist.

@sptndc maybe this is worth having a look at
