### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by tvooo** [tvooo/sublime-grunt#114]
I'm not maintaining sublime-grunt anymore. The folks over at Package Control suggested to still leave it in the registry, so I'm now looking for someone to take over maintenance of the package.

It's probably not much work keeping up with ST and Grunt developments; a bit of JS and Python knowledge is needed. If you want to take over, let me know in this issue.

Thanks :)

**Comment by sptndc** [comment]
Hi @tvooo, I'm ready to take over for maintenance of this package.

**Comment by tvooo** [comment]
Awesome, thanks. I see you've copied the repo already. I'll point people towards yours and make mine read-only then.
