### ISSUE TITLE
Open console when Grunt fails (e.g. with watch)

### ISSUE THREAD

**Issue by benfrain** [tvooo/sublime-grunt#18]
As I use Grunt with grunt-contrib-watch it would be handy if any problems with watch (undefined variables in Sass for example) that stop it being able to run popped up in the Sublime Text console. 

At present it runs and then when I close the console and introduce an error (as I'm prone to do ;) ) I get no notification that the watch task has aborted.

**Comment by tvooo** [comment]
Repository was moved to https://github.com/sptndc/sublime-grunt
Please re-file any issues that still exist.
