### ISSUE TITLE
Allow assigning a keyboard shortcut to a specific task

### ISSUE THREAD

**Issue by dsine-de** [tvooo/sublime-grunt#48]
Is it possible to add an "args" option in the keymap file to run a specific grunt task, so that you don't have to select a task from the list?

``` json
{ "keys": ["ctrl+b"], "command": "grunt", "args": {"task": "default"} }
```

Or is it possible to allow a setting for the default task name?

**Comment by tvooo** [comment]
Repository was moved to https://github.com/sptndc/sublime-grunt
Please re-file any issues that still exist.
