### ISSUE TITLE
ST3 and Linux - Grunt: Kill Running Process not working

### ISSUE THREAD

**Issue by vastbinderj** [tvooo/sublime-grunt#58]
I'm on Ubuntu 13 and ST3.  I have to switch to a terminal and kill the running nodemon task by process id.  

When I select Grunt: Kill Running Process, I see '[Cancelled]' in the build window, but it is not killing the nodemon process.  

Am I doing something wrong?

**Comment by tvooo** [comment]
Repository was moved to https://github.com/sptndc/sublime-grunt
Please re-file any issues that still exist.
