### ISSUE TITLE
"Gruntfile" is found, but "gruntfile" is not

### ISSUE THREAD

**Issue by dan-santana** [tvooo/sublime-grunt#59]
Actually, the plugin can find a file named "Gruntfile.js", but cannot find it when renamed to "gruntfile.js".

It would be good to be case-insensitive when looking for the Gruntfile, as this is the behavior when using grunt from command line.

**Comment by tvooo** [comment]
Repository was moved to https://github.com/sptndc/sublime-grunt
Please re-file any issues that still exist.
