### ISSUE TITLE
SublimeGrunt: JSON is malformed

### ISSUE THREAD

**Issue by polikin** [tvooo/sublime-grunt#74]
I don't know why I have this error.

SublimeGrunt: JSON is malformed

Could not expose gruntfile

I tried it with the command line and it's working fine.

**Comment by monta-ghost** [comment]
+1

**Comment by tvooo** [comment]
This usually happens when, for some reason, Grunt fails to run --- most likely, because a dependency is not installed. The error needs to be clearer then.

@monta-ghost can you check if that's the case for you?

**Comment by MrTango** [comment]
same error her. The dependencies should be fine, if I'm running Grunt in my project dir it works fine.
I don't see any cache file from the plugin in the project directory.

**Comment by ameliaoliveira** [comment]
Same error in here. And my grunt is ok into gbash.

**Comment by tvooo** [comment]
Repository was moved to https://github.com/sptndc/sublime-grunt
Please re-file any issues that still exist.
