### ISSUE TITLE
Piping the output to a new sublime window

### ISSUE THREAD

**Issue by Shadeslayer345** [tvooo/sublime-grunt#76]
I was wondering if there were plans to show the output in a new Sublime tab/window. Really helpful for longer outputs.

**Comment by lewiscowper** [comment]
I'd also like this, having a long running grunt watch or serve in a tab would be really helpful.

**Comment by tvooo** [comment]
Repository was moved to https://github.com/sptndc/sublime-grunt
Please re-file any issues that still exist.
