### ISSUE TITLE
Cannot run tasks with spaces in name

### ISSUE THREAD

**Issue by illiniguy** [tvooo/sublime-grunt#78]
Our grunt file has tasks with spaces in their name. This package will error out when trying to execute such a task.

If sample task name is 'localhost build'
Fails with message: 'Task 'localhost' not found.'

The reason is the grunt command that is run in main.py: on_done does not enclose the task name in quotes. I've modified my local copy to fix it. Sorry I don't have time to create a patch, just wanted to note.

**Comment by tvooo** [comment]
Repository was moved to https://github.com/sptndc/sublime-grunt
Please re-file any issues that still exist.
