### ISSUE TITLE
Grunt kill doesn't close all tasks

### ISSUE THREAD

**Issue by devjones** [tvooo/sublime-grunt#81]
I have a grunt task (grunt watch) which uses LiveReload.  LiveReload uses port 35729 to communicate with the browser.

I'm noticing that when I use the grunt kill command with this plugin that port 35729 remains open.  It should be closed along with any other tasks initiated by grunt.

When I do a hard kill from the command line using Ctrl-C, port 35729 is successfully closed.

**Comment by picard102** [comment]
For anyone trying to figure out how to kill live reload task, type curl localhost:25710/kill replacing the numbers with your own.
