### ISSUE TITLE
SublimeGrunt: JSON is malformed

### ISSUE THREAD

**Issue by int-np435** [tvooo/sublime-grunt#88]
I have a grunt project created by yeoman that works perfectly from the terminal (osx 10.8.5 here), but doesn't from sublime text 2. Apart from the error above there is nothing more than "Could not expose grunt file" and "no command for selector: noop:" in the sublime CLI.

Additional information: I'm behind corporate proxy and can't get package control to work properly. So I tried to install sublime-grunt by hand. Can't say if I succeeded with that thought ...

**Comment by neeln4j** [comment]
i also had this error but , i get resolved after reinstalling my nodejs and node-modules.
