### ISSUE TITLE
io.js Decode error: output not utf-8

### ISSUE THREAD

**Issue by ywzhaiqi** [tvooo/sublime-grunt#90]
After install io.js on Windows, An error has occurred.

>
[Decode error - output not utf-8]
[Finished in 0.1s with exit code 1]
[cmd: grunt --no-color concat]

**Comment by tvooo** [comment]
Can you tell if the task was still run? Maybe only the output did not work? Anyway, that seems to be an issue with io.js, I will have to investigate.

**Comment by ywzhaiqi** [comment]
it does’t work, I had to run `grunt` on cmd.

Thank you for help. Maybe I should reinstall node.js.
