### ISSUE TITLE
error: Could not read available tasks

### ISSUE THREAD

**Issue by huming0618** [tvooo/sublime-grunt#95]
This error came up when I click the "Grunt" in the command input.
I tried to check the source code for main.py, I found some error occurs when run the "run_expose", I print the output for the reference :

grunt --no-color --tasks "/Users/peter/Library/Application Support/Sublime Text 2/Packages/Grunt" expose:Gruntfile.js

> > Tasks directory "/Users/peter/Library/Application Support/Sublime Text 2/Packages/Grunt" not found.
> > Warning: Task "expose:Gruntfile.js" not found. Use --force to continue.

Is there any setting I were missing  before running it?

**Comment by tvooo** [comment]
Does this directory exist on your filesystem?

**Comment by huming0618** [comment]
No. "/Users/peter/Library/Application Support/Sublime Text 2/Packages/Grunt " doesn't exist

**Comment by tvooo** [comment]
Repository was moved to https://github.com/sptndc/sublime-grunt
Please re-file any issues that still exist.
