### ISSUE TITLE
Grunt task runner tab closed

### ISSUE THREAD

**Issue by benmb1984** [tvooo/sublime-grunt#96]
When I have a task running, a Grunt task tab will appear. But when I hit escape or want to search with Sublime (Ctrl + F) the Grunt task tab disappears.

I cant find a way to reopen the tab with the current running Grunt task.
Is there an option for this? 

Greetings, Ben

**Comment by tvooo** [comment]
Yes, you can reopen it via Tools -> Build Results -> Show Build Results. I should add this as a command, you're not the first one to ask :)

**Comment by benmb1984** [comment]
Great, thanks!
I hope we can pin this tab in the future.
