### ISSUE TITLE
Feature Request: Support configuration for showing only custom tasks in quick panel

### ISSUE THREAD

**Issue by jobrodesign** [tvooo/sublime-grunt#98]
Trying to setup a centralized build system for use by a growing team of designer/devs and trying to avoid the command line to keep everyone working inside Sublime.  It would be a great configuration setting to be able to hide non-custom tasks from the quick panel to manage signal vs noise.

**Comment by tvooo** [comment]
Repository was moved to https://github.com/sptndc/sublime-grunt
Please re-file any issues that still exist.
